sudo: required
dist: trusty

language: node_js
node_js:
- '6.1'

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y osmosis
- chmod a+x ./test/*.sh
- ./test/prepare-test.sh

install:
- npm install
